2020-01-29 12:21:20,802  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:21:26,490  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:22:50,293  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:23:37,318  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:24:37,035  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:25:03,512  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:28:32,599  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:37:18,969  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 12:37:20,969  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:00:43,763  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:01:02,184  ERROR  4298  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  147  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:02:04,229  ERROR  5497  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  148  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:03:45,304  ERROR  5541  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  148  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:05:00,062  ERROR  5541  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  148  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:10:35,532  ERROR  5541  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  148  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 13:10:54,738  ERROR  5541  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getValorTotal  148  FieldError("Cannot resolve keyword 'valor' into field. Choices are: agenda, ativo, id, nome, produtos, receita, tempo, valor_clinica, valor_mao_obra, valor_produtos, valor_total")  
2020-01-29 14:04:20,282  ERROR  7267  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  getDados  115  DoesNotExist('Receita matching query does not exist.')  
2020-01-29 14:05:50,252  ERROR  7267  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  getDados  115  DoesNotExist('Receita matching query does not exist.')  
2020-01-29 14:05:54,640  ERROR  7267  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  getDados  115  DoesNotExist('Receita matching query does not exist.')  
2020-01-29 14:06:11,505  ERROR  7267  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  getDados  115  DoesNotExist('Receita matching query does not exist.')  
2020-01-29 14:29:10,171  ERROR  7594  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getDados  118  DoesNotExist('Servico matching query does not exist.')  
2020-01-29 14:38:27,496  ERROR  7594  /Users/daniel/Nextcloud/Desenvolvimento/ERP/servico/funcoes/servico.py  getDados  118  DoesNotExist('Servico matching query does not exist.')  
2020-01-29 14:54:05,721  ERROR  8620  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  21  KeyError('paciente')  
2020-01-29 14:55:14,193  ERROR  8620  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  21  KeyError('paciente')  
2020-01-29 14:56:54,227  ERROR  8701  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  21  KeyError('paciente')  
2020-01-29 15:00:45,232  ERROR  8701  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  21  KeyError('valor_apagar')  
2020-01-29 15:02:02,784  ERROR  8701  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  21  KeyError('servicos')  
2020-01-29 15:03:55,594  ERROR  8904  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  18  ValueError('Cannot assign "\'140\'": "Receita.paciente" must be a "Paciente" instance.')  
2020-01-29 15:08:37,896  ERROR  9042  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  21  TypeError('Direct assignment to the forward side of a many-to-many set is prohibited. Use procedimentos.set() instead.')  
2020-01-29 15:09:06,850  ERROR  9063  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  22  TypeError('Direct assignment to the forward side of a many-to-many set is prohibited. Use procedimentos.set() instead.')  
2020-01-29 15:09:46,636  ERROR  9087  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  19  ValueError('Cannot assign "\'145\'": "Receita.paciente" must be a "Paciente" instance.')  
2020-01-29 15:13:11,544  ERROR  9087  /Users/daniel/Nextcloud/Desenvolvimento/ERP/financeiro/funcoes/financeiro.py  criar  19  ValueError('Cannot assign "\'145\'": "Receita.paciente" must be a "Paciente" instance.')  
